# Generated by Django 4.2.11 on 2026-03-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('identifier', models.CharField(blank=True, max_length=128)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='standards.standard')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controls',
            },
        ),
    ]
