# Generated by Django 5.2.12 on 2026-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='example_evidence',
            field=models.TextField(blank=True, default='', help_text='Example evidence text or document excerpts that demonstrate compliance.'),
        ),
        migrations.AddField(
            model_name='control',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords that indicate evidence for this control.', max_length=512),
        ),
        migrations.AddField(
            model_name='control',
            name='objective',
            field=models.TextField(blank=True, default='', help_text='The purpose or objective of this control.'),
        ),
        migrations.AddField(
            model_name='control',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='major', help_text='Severity level of this control for scoring and violation prioritization.', max_length=16),
        ),
    ]
