# Generated by Django 5.2.12 on 2026-03-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text="Liste des étapes de l'audit."),
        ),
    ]
