# Generated by Django 5.2.12 on 2026-03-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auditresult_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='status',
            field=models.CharField(
                choices=[
                    ('compliant', 'Conforme'),
                    ('partially_compliant', 'Partiellement Conforme'),
                    ('non_compliant', 'Non Conforme')
                ],
                default='non_compliant',
                help_text='Statut de conformité du document',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='missing_controls',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Liste des contrôles manquants.'
            ),
        ),
    ]
