# Generated by Django 5.2.12 on 2026-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_auditresult_status_missing_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='violation_details',
            field=models.JSONField(blank=True, default=list, help_text='Structured violations with severity and evidence.'),
        ),
    ]
