# Generated by Django 5.2.12 on 2026-03-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_atcnamevalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='detected_keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords successfully detected.'),
        ),
    ]
